### ISSUE TITLE
Assembler with a type containing a Bit

### ISSUE THREAD

**Issue by phanrahan** [cdonovick/peak#105]
I tried creating an assembler for the pdp8 isa. It fails, because there is a type which is product of Bits.

File "/Users/hanrahan/git/peak/peak/assembler/assembler.py", line 152, in _field
    width = isa.size
AttributeError: type object 'Bit' has no attribute 'size'

Should this work? Am I doing something wrong?

**Comment by cdonovick** [comment]
This has been fixed in master try rebasing.

**Comment by phanrahan** [comment]
Works.
