### ISSUE TITLE
Type mismatch when using hwtypes Product

### ISSUE THREAD

**Issue by jack-melchert** [cdonovick/peak#147]
```
from hwtypes import Product
import magma

Bit = magma.Bit

class test(Product):
    test_bit = Bit
       
test(Bit(1))
```

This should work right? It gives a type mismatch error saying that "Value VCC is not of type Bit".

**Comment by rsetaluri** [comment]
@jack-melchert this looks like from recent changes. Let me take a look.

But first, does using `magma.Product` rather than `hwtypes.Product` fix anything?

**Comment by jack-melchert** [comment]
Yep, using magma.Product works fine, its just the hwtypes.Product that causes an error.

**Comment by rsetaluri** [comment]
is that the issue? does `hwtypes.Product` allow subfields of anytime or only hwtypes ADTs?

cc @cdonovick

**Comment by rdaly525** [comment]
Product definitely allows any type. Many tests use 'str' and 'int'

**Comment by rsetaluri** [comment]
Ok, I'll investigate

**Comment by rsetaluri** [comment]
Yeah there's an issue where `isinstance(m.Bit(0), m.Bit)` evaluates to false which is really bad 😬 . I'll work on a fix

**Comment by cdonovick** [comment]
@rsetaluri might it have to do with the following change: https://github.com/phanrahan/magma/pull/643

**Comment by rsetaluri** [comment]
@cdonovick nah actually is a more recent change I made...however; the type system was broken even before any of this, e.g. if you tried the same with `Clock` before it would've broken.

**Comment by rsetaluri** [comment]
@jack-melchert can you check that this works using branch `mamga-fix-bit-const`?

**Comment by jack-melchert** [comment]
It seems to fix some of the issues I was having, but a (possibly unrelated) issue keeps cropping up. I get a AssertionError: (Out(Bits[1]), Bit) when using an Enum with only two fields. Something like this:

```
class Signed_t(Enum):
        unsigned = 0
        signed = 1
```
won't work for me.

**Comment by cdonovick** [comment]
Is that a magma Enum or hwtypes enum?

**Comment by jack-melchert** [comment]
Hwtypes

**Comment by cdonovick** [comment]
Can you generate minimal failing case?

**Comment by rsetaluri** [comment]
@jack-melchert 
```python
class Signed_t(Enum):
        unsigned = 0
        signed = 1
```

seems to work for me...

**Comment by jack-melchert** [comment]
`hwtypes-enum-bug` using test_magma_compile.py shows this bug. Its actually only when the Enum class has two options that are 0 and 1. 

For this example, if examples/demo_pes/pe7/isa.py has this Op class:
```
class Op(Enum):
    Add  = 1
    And  = 2
```
it works fine but if I change it to this:
```
class Op(Enum):
    Add  = 0
    And  = 1
```
it gives this error:

```
Traceback (most recent call last):
  File "/nobackup/melchert/lassen-env/lib/python3.7/site-packages/magma/ast_utils.py", line 54, in compile_function_to_file
    exec(code, defn_env)
  File ".magma/PE_comb.py", line 1, in <module>
    class PE_comb(m.Circuit):
  File ".magma/PE_comb.py", line 20, in PE_comb
    O0 = phi([O0, __magma_ssa_return_value_0[0]], io.inst.choice)
  File "/nobackup/melchert/lassen-env/lib/python3.7/site-packages/magma/operators.py", line 24, in mux
    return Mux(len(I), T, **kwargs)()(*I, S)
  File "/nobackup/melchert/lassen-env/lib/python3.7/site-packages/magma/generator.py", line 101, in __call__
    this = _make_type(cls, *args, **kwargs)
  File "/nobackup/melchert/lassen-env/lib/python3.7/site-packages/magma/generator.py", line 74, in _make_type
    cls.__init__(dummy, *args, **kwargs)
  File "/nobackup/melchert/lassen-env/lib/python3.7/site-packages/magma/mux.py", line 64, in __init__
    self.io.O @= T.unflatten(mux.O)
  File "/nobackup/melchert/lassen-env/lib/python3.7/site-packages/magma/bits.py", line 520, in unflatten
    return Bits[size](value)
  File "/nobackup/melchert/lassen-env/lib/python3.7/site-packages/magma/bits.py", line 52, in __call__
    result = super().__call__(*args, **kwargs)
  File "/nobackup/melchert/lassen-env/src/hwtypes/hwtypes/bit_vector_abc.py", line 28, in __call__
    return super().__call__(value, *args, **kwargs)
  File "/nobackup/melchert/lassen-env/lib/python3.7/site-packages/magma/bits.py", line 100, in __init__
    Array.__init__(self, *args, **kwargs)
  File "/nobackup/melchert/lassen-env/lib/python3.7/site-packages/magma/array.py", line 215, in __init__
    issubclass(type(self.T), type(type(t))), (type(t), self.T)
AssertionError: (Array[1, Out(Bit)], Bit)
```

**Comment by cdonovick** [comment]
Can you push any local changes you have to the branch?  pe7 has 4 ops

**Comment by jack-melchert** [comment]
Whoops, I forgot to commit local changes, should be fixed now.

**Comment by rsetaluri** [comment]
Got confirmation from @jack-melchert that this was fixed.
