### ISSUE TITLE
Annoyances in writing and introspecting peak programs.

### ISSUE THREAD

**Issue by rdaly525** [cdonovick/peak#16]
There are two issues here. 

1) Currently we need to wrap the peak program in a function which takes in the correct BitVector class. I think a better way would be to pass the appropriate BitVector type as an __init__ parameter to the peak class.

2) Currently we are supporting high level peak simulation using arbitrary python functions and peak simulation from the __call__ method of a Peak subclass. When generating the mapper and presumably for generating the RTL these two different use cases needs to be handled separately (mostly from using the name_outputs decorator)

**Comment by rdaly525** [comment]
One option that Lenny just mentioned is that we could use a separate decorator on arbitrary python functions that could just transform it into a common representation (a Peak class) so that syntactically it could still be different.

**Comment by cdonovick** [comment]
I believe everything should inherit from `Peak` and use` __call__`.  Multiple ways to do things means multiple ways to break things. 
>There should be one-- and preferably only one --obvious way to do it.

The Zen of Python

**Comment by phanrahan** [comment]
In terms of injecting the right type, I am open to better ways to do that. @cdonovick is probably the right person to handle this.

I am not sure I follow the second point. The idea is to make the init and call functions polymorphic. We could create multiple classes with different hwtypes, but we want all the code that is in init and call to be in one place.

**Comment by rdaly525** [comment]
The second point is just saying that there are two ways of creating the peak simulation function. One using the __call__ method of an inherited peak class (what you think of as sequential functions), and the other just using an arbitrary python function (what you think of as combinational functions). I am pointing out that from a mapper perspective, syntactically it is annoying to handle both cases. I would prefer that anytime we want to generate rewrite rules from coreir primitives to mapper primitives, these mapper primitives need to be described in peak by inheriting from the Peak class.

**Comment by cdonovick** [comment]
Pretty sure this is resolved
