### ISSUE TITLE
[Feature Request] Constrain rewrite rule generator values by path instead of type

### ISSUE THREAD

**Issue by rdaly525** [cdonovick/peak#160]
Previous API:

`arch_mapper = ArchMapper(arch_fc, constrain_constant_bv : tp.Option[None, tuple])`

Proposed API:

```
constraints = {
  path1: (BV4(0),BV4(1), BV4(2)),
  path2: Bit(0)
  path3: (MyEnum.A, MyEnum.B)
  ...
}
arch_mapper = ArchMapper(arch_fc, path_constraints=constraints)
```

Any unspecified (unconstrained) path will:
-Existentially quantified if it is a Const type. 
-Universally quantified otherwise

**Comment by rdaly525** [comment]
@jack-melchert, let me know if this would be sufficient

**Comment by jack-melchert** [comment]
Yep, that is exactly what I need.
