### ISSUE TITLE
Assembled Magma as a return type causes some errors

### ISSUE THREAD

**Issue by jack-melchert** [cdonovick/peak#176]
On branch magma_adt_return_type_bug
pytest tests/test_magma_adt_bug.py

Gives this error:
```
E         File "<unknown>", line 15
E           self_PE_MagmaADT[Tuple[UInt[(16, Bit)], UInt[(16, Bit)]], <class 'peak.assembler.assembler.Assembler'>, UInt, <Direction.Out: 1>](O0)
E                                                                     ^
E       SyntaxError: invalid syntax

/usr/lib/python3.7/ast.py:35: SyntaxError
```

It seems to only happen when instantiating a Peak class that has the output of type (Tuple[Data, Data], Bit) within another Peak class. See examples/demo_pes/pe6 for an example of a failing case. Doesn't throw an error when the output is just Tuple[Data, Data], which is interesting.

**Comment by rsetaluri** [comment]
looks like you're using `repr` of a type for code gen and that now has this `<...>` stuff?

**Comment by cdonovick** [comment]
I think its likely something in sequential.  I will investigate.

**Comment by cdonovick** [comment]
I remember we had a similar bug before but I thought I fixed it with:

https://github.com/phanrahan/magma/blob/master/magma/syntax/sequential.py#L251

**Comment by cdonovick** [comment]
I have tracked the bug down to https://github.com/phanrahan/magma/blob/master/magma/syntax/sequential.py#L55

**Comment by cdonovick** [comment]
I think the output types need to be run through the `TypeNamer`

**Comment by cdonovick** [comment]
Turns out I was wrong about needing to run things through the TypeName but should be fixed by my PR to magma.
