### ISSUE TITLE
Different behavior for rewrite rule solve() vs verify()

### ISSUE THREAD

**Issue by jack-melchert** [cdonovick/peak#183]
On branch: verify-vs-solve
pytest tests/test_aadt_mapping.py

The problem is that you can solve for a rewrite rule and get no solution. However, there can still be rewrite rules that pass the `rr.verify()` check. This happens when you need to tie an input to a constant for the verify check to pass. 

For example: 
A PE that implements `res = (a + b) * c`
An IR that requires `res = a + b`

Solving for a rewrite rule will fail because a, b, and c are not wrapped in the `Const() `function, so they can't take constant values. However, if you hand write a rewrite rule saying `c = 0`, it will pass. 

Not a critical bug as its pretty easy to just avoid ever constructing rewrite rules with constants where they shouldn't be, but probably should be fixed sometime.

**Comment by rdaly525** [comment]
This is an intended feature. Specifying a path constraint to a non-const type when discovering a rewrite rule indicates that the value of that path will *always* be the value of the port. If you want for the rewrite rule to be valid independent of the value of the path, you should not set a value for the path
