### ISSUE TITLE
[Question] RTL export support

### ISSUE THREAD

**Issue by Nic30** [cdonovick/peak#198]
Hello, are you able to generate an actual hardware from ISA description? I am missing some description about what this project actually does.

**Comment by cdonovick** [comment]
Yes, we can generate RTL.  We use the HDL magma to generate magma. There isn't documentation but we have tests for the code path.   

https://github.com/cdonovick/peak/blob/master/tests/test_magma.py

https://github.com/phanrahan/magma.

**Comment by Nic30** [comment]
Nice, I still do not know how to actually use this project, but I will keep eye on it. It looks interesting. I do have similar set of tools but I can not compare it now.
Are you somehow related to Stanford?

**Comment by cdonovick** [comment]
Yes, I am Stanford phd candidate.

**Comment by Nic30** [comment]
Thank you for the information, I looking forward to see this tool in action some day.

**Comment by cdonovick** [comment]
I would be happy to give you a tour of the tool at some point if you would be interested.

**Comment by Nic30** [comment]
Sure, I am a PhD student which is working with "hw compilers" for network apps, naturally this project interests me.

**Comment by cdonovick** [comment]
Cool! I am currently working on two submissions to ASPLOS so I am pretty time poor but once that is done I'd be happy to chat with you to see if there is anyway our tools could be useful.  You might also be interested in our HDL magma which I previously mentioned (more or less chisel in python).  It actually has documentation so is much more approachable.

**Comment by Nic30** [comment]
https://github.com/phanrahan/magma/issues/281
