### ISSUE TITLE
Mapper is extremely slow

### ISSUE THREAD

**Issue by Kuree** [cdonovick/peak#42]
For the metamapper, finding a single mapping for any op (even trivial ones like add -> add) takes multiple minutes on my local machine. It would be extremely useful if it was in a format like a `sqlite3` database or saved to disk so that it doesn't need to be regenerated every time someone runs the garnet flow. 

https://github.com/rdaly525/MetaMapper/issues/15

**Comment by rdaly525** [comment]
Resolved by serializing/caching rewrite rules
