### ISSUE TITLE
Add reset to peak description/RTL output

### ISSUE THREAD

**Issue by rsetaluri** [cdonovick/peak#51]

**Comment by rdaly525** [comment]
I think we should resolve this by adding a parameter to the magma.circuit.sequential() to indicate how to instance the registers and that the details of how to reset shouldn't be in peak.

For example maybe we could do something like:

`@magma.circuit.sequential(async_reset = True, async_reset_name="rst")`
Or something along these lines
@leonardt @rsetaluri, thoughts?

**Comment by rdaly525** [comment]
Similar thoughts on describing a global 'en'

**Comment by rdaly525** [comment]
This is a feature in magma. Closing
